version: 2
sources:
  - name: raw_openf1
    database: F1_ANALYTICS_DEV
    schema: RAW
    tables:
      - name: OPENF1_SESSIONS
      - name: OPENF1_DRIVERS
      - name: OPENF1_LAPS
      - name: OPENF1_PIT
      - name: OPENF1_STINTS
